apiVersion: apps/v1
kind: Deployment
metadata:
  name: getbirdimage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getbirdimage
  template:
    metadata:
      labels:
        app: getbirdimage
    spec:
      containers:
        - name: getbirdimage
          image: getbirdimage:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4200
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
