apiVersion: v1
kind: Service
metadata:
  name: getbirdimage
spec:
  selector:
    app: getbirdimage
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 32000
  type: NodePort

